--SELECT 100+5, 10-3, 30*2, 10/3
--FROM DUAL;
--SELECT 100+5, 10-3, 30*2, 10/3 FROM DUAL;
--SELECT dbms_random.value()*100 FROM DUAL;
--SELECT ENAME FROM EMP AS EMPLOYEE;
--SELECT ENAME AS "EMPLOYEE NAME" FROM EMP EMPLOYEE;
--SELECT * FROM EMP ORDER BY SAL;
--SELECT * FROM EMP ORDER BY SAL DESC;
--SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;
--SELECT ENAME, JOB, SAL, DEPTNO
--FROM EMP
--WHERE DEPTNO = 10;
--SELECT ENAME AS "ENAME2", JOB, SAL, DEPTNO
--FROM EMP
--WHERE DEPTNO = 20 AND JOB = 'ANALYST';
--SELECT * FROM EMP 
--WHERE SAL > 2500
--ORDER BY SAL;
--SELECT * FROM EMP
--WHERE ENAME >= 'M'
--ORDER BY ENAME;
--SELECT CHR(0), CHR(65), ASCII('a'), ASCII('A') FROM dual;
--SELECT * FROM EMP WHERE SAL =w 5000;
--SELECT * FROM EMP WHERE SAL!= 5000;
--SELECT * FROM EMP WHERE SAL<> 5000;
--SELECT * FROM EMP WHERE SAL^= 5000;
--SELECT * FROM EMP WHERE NOT SAL=5000;
--SELECT * FROM EMP
--WHERE SAL = (SELECT MAX(SAL) FROM EMP);
--SELECT * FROM EMP WHERE SAL = 5000 AND SAL = 3000;
--SELECT * FROM EMP WHERE SAL = 5000 OR SAL = 3000;
--SELECT * FROM EMP WHERE SAL IN (5000,3000);
--SELECT * FROM EMP WHERE JOB = 'ANALYST' OR JOB = 'KING' OR JOB = 'CLERK';
--SELECT * FROM EMP WHERE JOB IN ('MANAGER','KING','CLERK');
--SELECT * FROM NLS_DATABASE_PARAMETERS 
--WHERE PARAMETER = 'NLS_CHARACTERSET';
--SELECT * FROM EMP
--ORDER BY
--(CASE WHEN DEPTNO = 10 THEN 1
--ELSE 2 END), SAL DESC;
--SELECT * FROM DEPT;
--SELECT ENAME FROM EMP WHERE DEPTNO ='20';
--SELECT * FROM EMP WHERE ENAME LIKE 'M%';
--SELECT * FROM EMP WHERE COMM = NULL;
--SELECT * FROM EMP WHERE JOB = 'CLERK'
--UNION
--SELECT * FROM EMP WHERE JOB = 'SALESMAN'

--SELECT EMPNO
--FROM EMP WHERE DEPTNO = 10
--UNION
--SELECT EMPNO, SAL
--FROM EMP WHERE DEPTNO = 20

--SELECT EMPNO, ENAME, SAL, DEPTNO

--SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5)
--FROM EMP;

--SELECT '010-1234-5678' AS REPLACE_BEFORE
--, REPLACE ('010-1234-5678','-','') AS REPLACE_1
--, REPLACE('010-1234-5678','-') AS REPLACE_2
--FROM DUAL;

--SELECT 'Oracle', LPAD('Oracle',10, '#') AS LPAD_1
--, RPAD('Oracle',10,'#') AS RPAD_1
--, LPAD('Oracle', 10) AS LPAD_2
--, RPAD('Oracle', 10) AS RPAD_2
--FROM DUAL;

--SELECT EMPNO, ENAME, CONCAT(EMPNO, ENAME),
--CONCAT(EMPNO, CONCAT(':', ENAME))
--FROM EMP
--WHERE ENAME = 'SMITH';

--SELECT CEIL(3.14) AS CEIL, FLOOR(3.14) AS FLOOR,
--CEIL(-3.14) AS CEIL_M, FLOOR(-3.14) AS FLOOR_M
--FROM DUAL;

--SELECT SYSDATE AS NOW, SYSDATE-1 AS YESTERDAY, SYSDATE+1 AS TOMORROW
--FROM EMP;

--SELECT SYSDATE, ADD_MONTHS(SYSDATE, 3) FROM DUAL;
--SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 12*20) AS WORK10YEAR
--FROM EMP;

--SELECT EMPNO, ENAME, HIREDATE, SYSDATE 
--FROM EMP
--WHERE ADD_MONTHS(HIREDATE, 12*40) > SYSDATE;
--
--SELECT ENAME, HIREDATE, SYSDATE,
--MONTHS_BETWEEN(HIREDATE, SYSDATE)/12 AS YEAR1 


--SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM, NVL(COMM,0), SAL+NVL(COMM,0)
--FROM EMP;

--SELECT EMPNO, ENAME, COMM, NVL2(COMM, 'O', 'X'), NVL2(COMM, SAL*12+COMM, SAL*12)

/* 표준 SQL */
SELECT *
FROM EMP JOIN DEPT
	(USING DEPTNO)
ORDER BY EMPNO;
